FROM python:3.12

WORKDIR /app

COPY app.py .
COPY enterprise_models.py .

RUN pip install fastapi[all] litellm boto3

EXPOSE 8080

CMD ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8080", "--reload"]